name: gthumb-unofficial
base: core22
version: '3.12.4'
summary: An image viewer and browser utility for the GNOME environment
description: |
    gThumb is an image viewer and browser for the GNOME Desktop. It also includes an importer tool for transferring photos from cameras.
grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: armhf
    build-for: armhf

slots:
   dbus-gthumb:
      interface: dbus
      bus: session
      name: org.gnome.gThumb

apps:
  gthumb:
    command: usr/bin/gthumb
    desktop: usr/share/applications/org.gnome.gThumb.desktop
    plugs: [home, x11, desktop, desktop-legacy, removable-media, network]
    extensions: [ gnome ]
    slots: [ dbus-gthumb ]

parts:
  main:
    source: https://download.gnome.org/sources/gthumb/3.12/gthumb-3.12.4.tar.xz
    plugin: meson
    meson-parameters: [--prefix=/snap/gthumb-unofficial/current/usr]
    organize:
      snap/gthumb-unofficial/current/usr: usr

    override-prime: |
       craftctl default
       set -eux
       glib-compile-schemas usr/share/glib-2.0/schemas
       sed -i 's|Icon=org.gnome.gThumb|Icon=usr/share/icons/hicolor/scalable/apps/org.gnome.gThumb.svg|g' usr/share/applications/org.gnome.gThumb.desktop
       if [ -f usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1 ]; then
          execstack --clear-execstack usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1
       fi

    stage-packages:
      - desktop-file-utils
      - libjpeg9
      - libpng16-16
      - zlib1g
      - librsvg2-2
      - libwebp7
      - libraw-bin
      - libheif1
      - liblcms2-2
      - brasero
      - gsettings-desktop-schemas
      - libglib2.0-0

    build-packages:
      - libglib2.0-0
      - libpng-dev
      - libjpeg-dev
      - zlib1g-dev
      - libraw-dev
      - librsvg2-dev
      - libwebp-dev
      - libheif-dev
      - liblcms2-dev
      - libclutter-gtk-1.0-dev
      - libjpeg-dev
      - gsettings-desktop-schemas-dev
      - bison
      - flex
      - meson
      - libglib2.0-dev
      - gettext
      - itstool
