name: gthumb-unofficial
base: core24
version: '3.12.7'
summary: An image viewer and browser utility for the GNOME environment
description: |
    gThumb is an image viewer and browser for the GNOME Desktop. It also includes an importer tool for transferring photos from cameras.
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:

slots:
   dbus-gthumb:
      interface: dbus
      bus: session
      name: org.gnome.gThumb

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gthumb/extensions:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gthumb/extensions
  /usr/share/gthumb:
    symlink: $SNAP/usr/share/gthumb
  /usr/share/help:
    symlink: $SNAP/usr/share/help

apps:
  gthumb:
    command: usr/bin/gthumb
    desktop: usr/share/applications/org.gnome.gThumb.desktop
    plugs: [home, x11, desktop, desktop-legacy, removable-media, network]
    extensions: [ gnome ]
    slots: [ dbus-gthumb ]
    environment:
       DISABLE_WAYLAND: 1
       GIO_MODULE_DIR: ""

parts:
  main:
    source: https://download.gnome.org/sources/gthumb/3.12/gthumb-3.12.7.tar.xz
    plugin: meson
    meson-parameters: [--prefix=/usr]

    override-prime: |
       craftctl default
       set -eux
       glib-compile-schemas usr/share/glib-2.0/schemas
       sed -i 's|Icon=org.gnome.gThumb|Icon=usr/share/icons/hicolor/scalable/apps/org.gnome.gThumb.svg|g' usr/share/applications/org.gnome.gThumb.desktop
       if [ -f usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1 ]; then
          execstack --clear-execstack usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1
       fi

    stage-packages:
      - librsvg2-2
      - liblcms2-2
      - libjxl0.7
      - libraw23t64
      - gsettings-desktop-schemas
      - libexiv2-dev

    build-packages:
      - libraw-dev
      - librsvg2-dev
      - liblcms2-dev
      - libcolord-gtk-dev
      - libjxl-dev
      - meson
      - libexiv2-dev
      - gettext
      - bison
      - flex
      - itstool

  cleanup:
       after: [main]
       plugin: nil
       build-snaps:
         - gnome-46-2404
         - core24
       override-prime: |
         set -eux
         for snap in "gnome-46-2404" "core24"; do
             cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
         done
