name: gthumb-unofficial # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '3.12.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: An image viewer and browser utility for the GNOME environment
description: |
    gThumb is an image viewer and browser for the GNOME Desktop. It also includes an importer tool for transferring photos from cameras. 
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
   dbus-gthumb:
      interface: dbus
      bus: session
      name: org.gnome.gThumb

apps:
  gthumb:
    command: usr/bin/gthumb
    desktop: usr/share/applications/org.gnome.gThumb.desktop
    plugs: [home, x11, desktop, desktop-legacy, removable-media, network]
    extensions: [ gnome ]
    slots: [ dbus-gthumb ]

parts:
  main:
    source: https://download.gnome.org/sources/gthumb/3.12/gthumb-3.12.2.tar.xz
    # See 'snapcraft plugins'
    plugin: meson
    meson-parameters: [--prefix=/snap/gthumb-unofficial/current/usr]
    organize:
      snap/gthumb-unofficial/current/usr: usr

    override-pull: |
       rm -f /etc/resolv.conf
       echo "nameserver 192.168.1.11" > /etc/resolv.conf
       sysctl -w net.ipv6.conf.all.disable_ipv6=1
       sysctl -w net.ipv6.conf.default.disable_ipv6=1
       sysctl -w net.ipv6.conf.lo.disable_ipv6=1
       sed -i '/archive/d' /etc/hosts
       sed -i '/security/d' /etc/hosts
       echo "213.202.193.253 archive.ubuntu.com" >> /etc/hosts
       echo "213.202.193.253 security.ubuntu.com" >> /etc/hosts
       snapcraftctl pull

    override-prime: |
       craftctl default
       set -eux
       glib-compile-schemas usr/share/glib-2.0/schemas
       sed -i 's|Icon=org.gnome.gThumb|Icon=usr/share/icons/hicolor/scalable/apps/org.gnome.gThumb.svg|g' usr/share/applications/org.gnome.gThumb.desktop


    stage-packages:
      - desktop-file-utils
      - libjpeg9
      - libpng16-16
      - zlib1g
      - librsvg2-2
      - libwebp7
      - libraw-bin
      - libheif1
      - liblcms2-2
      - brasero
      - gsettings-desktop-schemas
      - libglib2.0-0

    build-packages:
      - libglib2.0-0
      - libpng-dev
      - libjpeg-dev
      - zlib1g-dev
      - libraw-dev
      - librsvg2-dev
      - libwebp-dev
      - libheif-dev
      - liblcms2-dev
      - libclutter-gtk-1.0-dev
      - libjpeg-dev
      - gsettings-desktop-schemas-dev
      - bison
      - flex
      - meson
      - libglib2.0-dev
      - gettext
      - itstool
